model_type: 'DIEN_CTR'
train_file: "data/train_data"
test_file: "data/test_data"
uid_voc: "data/uid_voc.json"
mid_voc: "data/item_voc.json"
cat_voc: "data/cate_voc.json"
tag_voc: "data/tag_voc.json"
batch_size: 1024
learning_rate: 0.001
embeding_size: 32
enable_shuffle: False
hidden_size: 36
attention_size: 36
maxlen: 10
minlen: 1
targetLen: 10
negseq_length: 5
tags_length: 5
seed: 2
test_iter: 5
save_iter: 20
epochs: 2
best_model_path: "best_model/ckpt"
logdir: "logdir"
max_steps: 500
lr_decay_steps: 500
