train_file: "data/train_splitByUser"
test_file: "data/test_splitByUser"
uid_voc: "data/uid_voc.json"
mid_voc: "data/item_voc.json"
cat_voc: "data/cate_voc.json"
tag_voc: "data/tag_voc.json"
item_info: "data/item_info.json"
n_utype: 20
uid_embedding_dim: 32
utype_embedding_dim: 4
mid_embedding_dim: 32
cat_embedding_dim: 4
tag_embedding_dim: 2
use_negsampling: True
enable_uid: False
enable_tag: True
hidden_size: 64
attention_size: 64
batch_size: 1024
maxlen: 100
minlen: 1
feats_dim: 747
negseq_length: 5
tags_length: 5
model_type: 'DIEN'
enable_shuffle: True
seed: 2
test_iter: 100
save_iter: 100
epochs: 2
best_model_path: "best_model/ckpt"
logdir: "logdir"
max_steps: 1000
lr_decay_steps: 300