train_file: "data/train_splitByUser/*.gz"
test_file: "data/test_splitByUser/*.gz"
uid_voc: "data/uid_voc.json"
mid_voc: "data/item_voc.json"
cat_voc: "data/cate_voc.json"
item_info: "data/item_info.json"
uid_embedding_dim: 128
mid_embedding_dim: 64
cat_embedding_dim: 16
hidden_size: 64
attention_size: 64
batch_size: 512
maxlen: 100
minlen: 1
feats_dim: 207
model_type: 'DIEN'
enable_shuffle: True
seed: 2
test_iter: 100
save_iter: 100
epochs: 2
model_path: "output/dnn_save_path/ckpt"
best_model_path: "output/dnn_best_model/ckpt"
logdir: "output/dnn_logdir"
max_steps: 1000