train_file: "data/train_splitByUser"
test_file: "data/test_splitByUser"
uid_voc: "data/uid_voc.json"
mid_voc: "data/item_voc.json"
cat_voc: "data/cate_voc.json"
item_info: "data/item_info.json"
batch_size: 128
maxlen: 100
minlen: 1
model_type: 'DIEN'
seed: 2
