train_file: "data/train_splitByUser"
test_file: "data/test_splitByUser"
uid_voc: "data/uid_voc.json"
mid_voc: "data/item_voc.json"
cat_voc: "data/cate_voc.json"
item_info: "data/item_info.json"
batch_size: 128
maxlen: 100
minlen: 1
model_type: 'DIEN'
enable_shuffle: False
seed: 2
test_iter: 100
save_iter: 100
epochs: 2
model_path: "output/dnn_save_path/ckpt_noshuff"
best_model_path: "output/dnn_best_model/ckpt_noshuff"
logdir: "output/dnn_logdir"