model_type: 'SESS'
train_file: "data/train_data"
test_file: "data/test_data"
uid_voc: "data/uid_voc.json"
mid_voc: "data/item_voc.json"
cat_voc: "data/cate_voc.json"
tag_voc: "data/tag_voc.json"
n_utype: 20
batch_size: 1024
learning_rate: 0.001
uid_embedding_dim: 32
mid_embedding_dim: 32
cat_embedding_dim: 4
tag_embedding_dim: 20
hidden_size: 18
attention_size: 64
enable_shuffle: True
use_negsampling: False
use_pair_loss: False
enable_uid: False
enable_tag: False
maxlen: 10
minlen: 1
targetLen: 10
negseq_length: 5
tags_length: 5
seed: 2
test_iter: 1
save_iter: 20
epochs: 2
best_model_path: "best_model/ckpt"
logdir: "logdir"
max_steps: 1000
lr_decay_steps: 1000
