model_type: 'DIEN'
train_file: "data/train_splitByUser"
test_file: "data/test_splitByUser"
uid_voc: "data/uid_voc.json"
mid_voc: "data/item_voc.json"
cat_voc: "data/cate_voc.json"
tag_voc: "data/tag_voc.json"
n_utype: 20
batch_size: 1024
learning_rate: 0.01
uid_embedding_dim: 32
mid_embedding_dim: 32
cat_embedding_dim: 4
tag_embedding_dim: 20
hidden_size: 64
attention_size: 64
enable_shuffle: True
use_negsampling: True
use_pair_loss: True
enable_uid: True
enable_tag: True
maxlen: 100
minlen: 1
targetLen: 10
negseq_length: 5
tags_length: 5
seed: 2
test_iter: 100
save_iter: 100
epochs: 2
best_model_path: "best_model/ckpt"
logdir: "logdir"
max_steps: 5000
lr_decay_steps: 1000